### ISSUE TITLE
Recognition of non human moving objects in RoomAlive-Unity

### ISSUE THREAD

**Issue by CaptainJeffo** [Microsoft/RoomAliveToolkit#55]
While testing the capability's of RoomAlive on recognising non human moving objects in Unity :

The code display's a range of sub meshes who seem to be grouped on several horizontal lines, instead of clear defined object meshes grouped by object.

Is there a better solution?  

It also generates a lot of noise = small points - lines who are non existing in the scene.

**Comment by hbenko** [comment]
Unity has a limit on the number of vertices that a mesh can contain, therefore our code meshes the depth mesh in strips, but they are all grouped together under the same parent object.

Noise is due to Kinect capture, If you look in the [RoomAliveToolkit/RoomAliveToolkitForUnity/RoomAliveUnity/Assets/RoomAliveToolkit/Shaders/DepthMeshSurfaceShader.shader](RoomAliveToolkit/RoomAliveToolkitForUnity/RoomAliveUnity/Assets/RoomAliveToolkit/Shaders/DepthMeshSurfaceShader.shader )  there is a property called _DepthCuttofThreshold which you can decrease to be more aggressive in filtering triangles that straddle bigger jumps. By default it is set to 10 cm.
