### ISSUE TITLE
How to use RoomAlive-Unity to achieve three-dimensional reproduction

### ISSUE THREAD

**Issue by 59198680** [Microsoft/RoomAliveToolkit#57]
Hello,Sir :)
I wanna put three scanning figures (I got them from 3 kinets scanning) together, but it doesn`t looks good. So , what should I do to successfully achieve 3D reconstruction? Would you mind asisting me ? :)
These are some screenshots ,This item is a water bottle，but the result is we got so many burrs:
![20170428_213741](https://cloud.githubusercontent.com/assets/15572021/25531227/95f7078c-2c5b-11e7-9489-fc4a6858cfdd.jpg)
![20170428_213724](https://cloud.githubusercontent.com/assets/15572021/25531395/1dea509a-2c5c-11e7-8dce-aed7874f722b.jpg)
![20170428_213703](https://cloud.githubusercontent.com/assets/15572021/25531400/2097cc28-2c5c-11e7-8cfe-a5c886663175.jpg)
 :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :) :)

**Comment by 59198680** [comment]
somebody help me?thank

**Comment by hbenko** [comment]
RoomAlive Toolkit is not really designed for 3D reconstruction tasks since it doesn't treat depth meshes as a combined reconstruction, but each camera's depth mesh is treated independently. This is why you are getting a lot of noise around the edges where the depth estimation is wrong.  I'd suggest you look into the shaders we currently use for rendering each depth mesh and try to adjust the maximum depth threshold that it uses for meshing (currently set to 10 cm I believe). That will clean things up a bit, but likely not produce the tight results you would want. 

Ultimately, you should probably look into creating a new mesh script that creates a unified solid mesh out of multiple depth views. We don't have support for that right now. If you do it, please share it back as that would be a great addition to the toolkit.

**Comment by hbenko** [comment]
Also... water bottle is probably very noisy and small object to capture with a depth camera in the first place (due to its translucency and specularity). I'd try something that is solid and lambertian to begin with, maybe a box or a piece of furniture?

**Comment by 59198680** [comment]
Thanks for your help!
